<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/10/12
 * Time: 14:24
 */

namespace app\apihome\controller;


use think\Db;

class Cart extends Home
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /*
     * 购物车商品列表
     * **/
    public function index()
    {
        $op=_param('op','','display');
        $user_id=$this->uid;
        if($op=='add'){
            $cart_id=intval($_POST['cart_id']);
            $data['num']=intval($_POST['num']);

            $data['uid']=$user_id;
            if(!$data['num']){
                $data['num']=1;
            }
            if($cart_id){
                $rs=db("cart")->where(array('id'=>$cart_id))->update(array('num'=>$data['num']));
            }else{
                $data['gid']=_param('gid','商品不能为空');
                $good=Db::name('good')->where('id',$data['gid'])
                    ->field('id,sid,goods_option,price')->find();
                if(!$good){
                    _internalError('数据错误');
                }
                $data['sid']=$good['sid'];
                $data['goodoptions']=$good['goodoptions']?$good['goodoptions']:'';
                $data['money']=$good['price']*$data['num'];
            }

            $id=db("cart")->where(array('gid'=>$data['gid'],'uid'=>$user_id))->value("id");
            if($id){
                $data['addtime']=time();
                $rs=db("cart")->where(array('id'=>$id))->update($data);
            }else{
                $data['addtime']=time();
                $rs=db("cart")->insert($data);
            }
            if($rs){
                _success('操作成功',200,'');
            }
            _internalError('未知错误');
        }elseif($op=="del"){
            $cart_id=_param('cart_id','购物车信息错误');

            $cartw['id']=array('in',$cart_id);
            db("cart")->where($cartw)->delete();
            _success('删除成功');

        }else{
            $cart=Db::name('cart')->where('uid',$user_id)->group('sid')->select();
            foreach ($cart as $key=>$val){
                $cart[$key]['shop']=Db::name('supuser')->where('sid',$val['sid'])->field('sid,shopname')->find();
                $goods=Db::name('cart')->where('uid',1)->where('sid',$val['sid'])->select();
                foreach ($goods as $k=>$v){
                    $good=$this->getgooddet($v['id']);
                    $goods[$k]['good']=$good;

                    $cart[$key]['goods']=$goods;
                }
            }
            _success('获取成功','200',$cart);
        }

    }

    /*
     * 商品点赞
     */
    public function goodzan(){
        $user_id=$this->uid;
        $goodid=_param('gid','商品数据不能为空');
        $d['uid']=$user_id;
        $d['gid']=$goodid;
        $d['type']=1;

        $old=Db::name('goodzan')->where($d)->find();
        if($old){
          $rs=  Db::name('goodzan')->where($d)->delete();
            $msg="取消成功";

        }else{
            $d['addtime']=time();
            $rs=Db::name('goodzan')->insert($d);
            $msg="点赞成功";
        }

         if($rs){
            _success($msg);
         }
    }

    /*
     * 商品收藏
     */
    public function goodcoll(){
        $user_id=$this->uid;
        $goodid=_param('gid','商品数据不能为空');
        $d['uid']=$user_id;
        $d['gid']=$goodid;
        $d['type']=2;

        $old=Db::name('goodzan')->where($d)->find();
        if($old){
            $rs=  Db::name('goodzan')->where($d)->delete();
            $msg="取消成功";

        }else{
            $d['addtime']=time();
            $rs=Db::name('goodzan')->insert($d);
            $msg="收藏成功";
        }

        if($rs){
            _success($msg);
        }
    }
    /*
     * 取消商品收藏
     */
    public function delgoodcoll(){
        $user_id=$this->uid;
        $goodid=_param('gid','商品数据不能为空');
        $d['uid']=$user_id;
        $d['gid']=$goodid;
        $d['type']=2;
        $old=Db::name('goodzan')->where($d)->find();
        if($old){
            $rs=  Db::name('goodzan')->where($d)->delete();
        }else{
            $d['addtime']=time();
            $rs=Db::name('goodzan')->insert($d);
        }

        if($rs){
            _success('操作成功');
        }
    }

    public function getcart(){

        $cart=Db::name('cart')->where('uid','1')->group('sid')->select();
        foreach ($cart as $key=>$val){
            $cart[$key]['shop']=Db::name('supuser')->where('sid',$val['sid'])->field('sid,shopname')->find();
            $goods=Db::name('cart')->where('uid',1)->where('sid',$val['sid'])->select();
            foreach ($goods as $k=>$v){
                $good=$this->getgooddet($v['id']);
                $goods[$k]['good']=$good;

            $cart[$key]['goods']=$goods;
              }
        }
        _success('操作成功','',$cart);
    }
}