<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/10/12
 * Time: 14:47
 */

namespace app\apihome\controller;


use think\Db;

class Category extends Base
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /*
     * 分类列表
     */
    public function index(){
          $category=Db::name('category')->where('pid','0')->select();
          foreach ($category as $key=>$val){
              $category[$key]['children']=Db::name('category')->where('pid',$val['id'])->select();
              $category[$key]['img']=array();
              if($val['photo_x']){
                  $category[$key]['img']=__DATAURL__.$val['photo_x'];
              }
              $category[$key]['ad']=array();
              $category[$key]['ad']=Db::name('ad')->where('tid','4')->where('catid',$val['id'])->select();

          }
         $data=array(
              'category'=>$category
          );
          _success('获取成功','200',$data);
    }
    /*
     * 分类下商品
     */
    public function category(){
       $catid=_param('catid','','1',false);
       $data=$this->getgoodlist(1,0,$catid,'',1,'6','');
    }

}