<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/10/12
 * Time: 14:12.
 */

namespace app\apihome\controller;

use think\Db;

class Homeindex extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        //广告
        $adv = db('ad')->where(['tid' => 1])->order('sortorder desc')->select();
        foreach ($adv as &$v) {
            if ($v['img']) {
                $v['img'] = __DATAURL__.$v['img'];
            }
        }
        $img = db('ad')->where(['tid' => 3])->find();
        if ($img) {
            $img['img'] = __DATAURL__.$img['img'];
        }
        $bigadv = db('ad')->where(['tid' => 5])->find();
        if ($bigadv) {
            $bigadv['img'] = __DATAURL__.$bigadv['img'];
        }

        $csadv = db('ad')->where(['tid' => 6])->order('sortorder desc')->limit(2)->select();
        foreach ($csadv as &$v) {
            if ($v['img']) {
                $v['img'] = __DATAURL__.$v['img'];
            }
        }
        //分类
        $cates = db('category')->where(['is_show' => 1, 'is_delete' => 0, 'pid' => '0'])->order('sort asc')->select();
        foreach ($cates as &$v) {
            if ($v['photo_x']) {
                $v['photo_x'] = __DATAURL__.$v['photo_x'];
            }
        }
        $goodtypes = Db::name('Catetype')->order('sorts desc')->select();
        $hotgoods = $this->getgoodlist('0', 1, 0);

        $qggoods = $this->getgoodlist('0', 2, 0);
        $hotshops = $this->getshoplist('0', 2, 0);
        //购物车数据

        $num = db('cart')->count();
        $num = $num ? $num : 0;
        $data = [
            'adv' => $adv, //广告
            'img' => $img, //专题图片
            'cates' => $cates, //分类
            'bigadv' => $bigadv, //中间大图
            'spricadv' => $csadv, //中间小图
            'goodtypes' => $goodtypes, //首页栏目
            'hotgoods' => $hotgoods, //商品
            'qggoods' => $qggoods, //抢购商品
            'hotshops' => $hotshops, //热门店铺
            'cartnum' => $num, //购物车数量
        ];
        _success('获取成功', '', $data);
    }

    public function newbigpic()
    {
        $adv = Db::name('info')->where('id', '1')->field('pic_url,pic_time,pic_img')->find();
        $adv['newimg'] = [];
        if ($adv['pic_img']) {
            $adv['newimg'] = __DATAURL__.$adv['pic_img'];
        }
        $data = [
            'adv' => $adv, //广告
        ];
        _success('获取成功', '', $data);
    }

    /*
     * 商品列表
     *
     */
    public function goodlist()
    {
        $key = _param('k', '关键词', '', false);
        if (!mb_check_encoding($key, 'utf-8')) {
            $key = iconv('gb2312', 'utf-8', $key);
        }
        $type = _param('t', '类型', '', false);
        $page = _param('page', '分页', '1', false);
        $sid = _param('sid', '商家', '', false);
        $tj = _param('tj', '推荐类型', '', false);
        $data = $this->getgoodlist('1', $tj, $type, $key, $page, 6, $sid);
    }

    /*
     * 商品详情
     */
    public function gooddetail()
    {
        $goodid = _param('gid', '商品信息错误');
        $good = Db::name('good')->where('id', $goodid)->find();
        if (!$good) {
            _internalError('商品信息错误');
        }
        if ($good['is_delete'] == 2 || $good['is_show'] == 2) {
            _internalError('商品暂停销售');
        }
        $n = [];
        if ($good['photo_x']) {
            $img2 = explode(',', $good['photo_x']);
            foreach ($img2 as $k => $v) {
                $n[] = __DATAURL__.$v;
            }
        }
        $good['piccs'] = $n; //图片集1
        //图片轮播数组
        $img = explode(',', trim($good['photo_string'], ','));
        $b = [];
        if ($good['photo_string']) {
            foreach ($img as $k => $v) {
                if (strpos($v, 'http') !== false) {
                    $b[] = $v;
                } else {
                    $b[] = __DATAURL__.$v;
                }
            }
        } else {
            $b[] = '';
        }
        $good['img_arr'] = $b; //图片轮播数组
        $content = str_replace('/ueditor/', __UEDITORURL__, $good['content']);
        $good['content'] = $content;
        $good['xiaoliang'] = 100;
        $good['zan'] = 180;
        $good['shop'] = Db::name('supuser')->where('sid', $good['sid'])->field('sid,shopname,headimgurl')->find();
        if ($good['shop']['headimgurl']) {
            $good['shop']['headimgurl'] = __DATAURL__.$good['shop']['headimgurl'];
        }
        $w['gid'] = $goodid;
        $w['uid'] = 1;
        $wz['type'] = 1;
        $wc['type'] = 2;
        $good['is_zan'] = 0;
        $good['is_collect'] = 0;
        $good['is_zan'] = Db::name('goodzan')->where($w)->where($wz)->count();
        $good['is_collect'] = Db::name('goodzan')->where($w)->where($wc)->count();
        $comment = [];
        $data = [
            'goods' => $good,
            'comment' => $comment,
            'commentnum' => 10,
            'webtitle' => $good['title'].'商品信息',
        ];
        _success('获取成功', 200, $data);
    }

    /*
    *商店列表
     */
    public function shoplist()
    {
        $key = _param('k', '关键词', '', false);
        $type = _param('t', '类型', '', false);
        $page = _param('page', '分页', '1', false);
        $data = $this->getshoplist('1', '0', $type, $key, $page, 6);
    }

    /*
     * 店铺首页
     */
    public function shop()
    {
        $sid = _param('sid', '商户数据错误');
        $supuser = Db::name('supuser')->where(['sid' => $sid])
            ->field('sid,headimgurl,detail,type,shopname,bigpic,piccs,city,address')->find();
        if (!$supuser) {
            _internalError('数据错误');
        }
        unset($supuser['password']);
        $b = [];
        if ($supuser['piccs']) {
            $img = explode(',', $supuser['piccs']);
            foreach ($img as $k => $v) {
                $b[] = __DATAURL__.$v;
            }
        }
        $supuser['pics_arr'] = $b;
        if ($supuser['bigpic']) {
            $supuser['bigpic'] = __DATAURL__.$supuser['bigpic'];
        }
        $supuser['headimgurl2'] = '';
        if ($supuser['headimgurl']) {
            $supuser['headimgurl2'] = $supuser['headimgurl'];
            $supuser['headimgurl'] = __DATAURL__.$supuser['headimgurl'];
        }
        $supuser['ways'] = [
            '自提', '快小驴专车', '快小驴物流',
        ];
        $supuser['xiaoliang'] = 200;
        $supuser['yunfei'] = '单件12元';
        $supuser['posttime'] = '次日达';
        $supuser['posttag'] = '油费补贴';
        $data = [
            'shop' => $supuser,
            'shopcate' => $this->shopcate($sid),
            'webtitle' => '店铺信息',
        ];
        _success('获取成功', '200', $data);
    }

    /*
     * 店铺商品
     */
    public function shopgood()
    {
        $sid = _param('sid', '商户数据错误');
        $type = _param('t', '类型', '', false);
        $page = _param('page', '分页', '1', false);
        $data = $this->goodlist('1', '0', $type, '', $page, 6, $sid);
    }

    /*
     * 专题页
     */
    public function spichlist()
    {
        $model = Db::name('info');
        $goodid = '';
        $item = $model->where('id', 1)->field('id,zt_name,zt_pic,zt_desc')->find();
        $item['newimg'] = [];
        if ($item['zt_pic']) {
            $item['newimg'] = __DATAURL__.$item['zt_pic'];
        }
        $ztType = Db::name('shopzt')->where('type', 3)->select();
        if ($ztType) {
            $g = array_column($ztType, 'goodid');
            $goodStr = implode(',', $g);
            $goodId = $goodStr;
            foreach ($ztType as $key => $val) {
                $ztType[$key]['good'] = $this->getNewGoodlist($val['goodid']);
            }
        }
        $ztShop = Db::name('shopzt')->where('type', '2')->find();
        $ztShop['shops'] = $this->getNewShopList($ztShop['goodid']);
        $ztGood = Db::name('shopzt')->where('type', '1')->find();
        $ztGood['good'] = $this->getNewGoodlist($ztShop['goodid']);
        $data = [
            'item' => $item, //专题说明
            'zttype' => $ztType, //专题商品类型（里面的good就是类型下商品）
            'ztshop' => $ztShop, //专题推荐店铺
            'ztgood' => $ztGood, //专题推荐主要商品

            'webtitle' => '专题页面',
        ];

        _success('获取成功', '200', $data);
    }

    /*
    *商品列表
     *
     *
    */
    public function getNewGoodlist($gid)
    {
        $where['is_show'] = 1; //未隐藏
        $where['is_delete'] = 1; //未删除
        $where['id'] = ['in', $gid];

        $goods = Db::name('good')->where($where)
            ->order('sort desc')->select();
        foreach ($goods as $key => $val) {
            $goods[$key]['pic'] = '';
            if ($val['photo_x']) {
                $img = explode(',', $val['photo_x']);
                $goods[$key]['pic'] = __DATAURL__.$img[0];
            }
            $shop = Db::name('supuser')->where('sid', $val['sid'])->field('sid,shopname,headimgurl')->find();
            if ($shop['headimgurl']) {
                $shop['headimgurl'] = __DATAURL__.$shop['headimgurl'];
            }
            $goods[$key]['shop'] = $shop;
        }

        return $goods;
    }

    /*
         *商家列表
          * aj:是否接口返回
          * $tj：推荐
          * $type:分类
          * key:关键词
          *
         */
    public function getNewShopList($sid)
    {
        $where['sid'] = ['in', $sid];

        $shops = Db::name('supuser')->where($where)->order('sort desc')->field('sid,shopname,headimgurl')->select();

        foreach ($shops as $key => $val) {
            $shops[$key]['xiaoliang'] = 100;
            $shops[$key]['desta'] = '2km';
            $shops[$key]['pic'] = '';
            if ($val['headimgurl']) {
                $shops[$key]['pic'] = __DATAURL__.$val['headimgurl'];
            }
            $b = [];
        }

        return $shops;
    }
}
