<?php

namespace app\apihome\controller;

use think\Controller;

class Login extends Controller
{
    protected function _initialize()
    {
        $this->pracetkey = 'kuaixiaol1210';
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //***************************
    //  授权登录接口
    //***************************
    public function authlogin()
    {
        $openid = $_REQUEST['openid'];
        if (!$openid || $openid == 'undefined') {
            _internalError('授权失败', '503', '');
            //echo json_encode(array('status'=>0,'err'=>'授权失败！'.__LINE__));
            //exit();
        }
        $con = [];
        $con['openid'] = trim($openid);
        $uid = db('user')->where($con)->value('uid');
        if ($uid) {
            $userinfo = db('user')->where('uid='.intval($uid))->find();
            if (intval($userinfo['del']) == 1) {
                _internalError('账号异常', '504', '');
            }
            if ($userinfo['mobile']) {
                $err['id'] = intval($uid);
                $err['mobile'] = $userinfo['mobile'];
                if ($uid) {
                    $data = [
                        'iss' => '',
                        'iat' => time(),
                        'exp' => time() + 7 * 86400,
                        'jti' => md5(uniqid('JWT').time()),
                        'data' => $uid,
                    ];
                    $t = JWT::encode($data, $this->pracetkey);
                    _success('授权登陆成功', 200, $t);
                }
                _success('授权成功', '', $err);
            } else {
                _success('授权成功,请绑定手机号', '201', $err);
            }

            exit();
        } else {
            $data = [];
            $data['nickname'] = $_REQUEST['NickName'];
            $data['headimgurl'] = $_REQUEST['HeadUrl'];
            //$data['sex'] = $_REQUEST['gender'];
            $data['openid'] = $openid;
            $data['addtime'] = time();
            if (!$data['openid']) {
                _internalError('授权失败', '503');
            }
            $res = db('user')->insertGetId($data);
            if ($res) {
                $err = [];
                $err['ID'] = intval($res);
                $err['mobile'] = '';
                _success('授权成功,请绑定手机号', '201', $err);
            } else {
                _internalError('授权失败', '503');
            }
        }
    }

    //***************************
    //  获取sessionkey 接口
    //***************************
    public function getsessionkey()
    {
        $info = db('info')->where('id', 1)->field('appid,appsecret')->find();

        $code = trim($_REQUEST['code']);
        if (!$code) {
            echo json_encode(['status' => 0, 'err' => '非法操作！']);
            exit();
        }

        if (!$info['appid'] || !$info['appsecret']) {
            echo json_encode(['status' => 0, 'err' => '非法操作！'.__LINE__]);
            exit();
        }

        $get_token_url = 'https://api.weixin.qq.com/sns/jscode2session?appid='.$info['appid'].'&secret='.$info['appsecret'].'&js_code='.$code.'&grant_type=authorization_code';
        $res = $this->httpget($get_token_url);
        echo  $res;
        exit();
    }

    public function httpget($url)
    {
        $oCurl = curl_init();
        curl_setopt($oCurl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($oCurl, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($oCurl, CURLOPT_SSLVERSION, 1); //CURL_SSLVERSION_TLSv1
        curl_setopt($oCurl, CURLOPT_URL, $url);
        curl_setopt($oCurl, CURLOPT_RETURNTRANSFER, 1);
        $sContent = curl_exec($oCurl);
        $aStatus = curl_getinfo($oCurl);
        curl_close($oCurl);
        if (intval($aStatus['http_code']) == 200) {
            return $sContent;
        } else {
            return false;
        }
    }
}
