<?php
/*
 * @Descripttion:
 * @version:
 * @Author: zfc
 * @Date: 2020-10-12 14:44:52
 * @LastEditors: zfc
 * @LastEditTime: 2020-12-10 16:32:54
 */
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/10/12
 * Time: 14:36
 * desc:用户中心.
 */

namespace app\apihome\controller;

class User extends Home
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /*
     * 个人中心
     */
    public function index()
    {
    }

    /*
     * 修改资料
     */
    public function changeuser()
    {
    }

    /*
     * 我的评价
     */
    public function mycomment()
    {
    }

    /*
     * 我的推广码
     */
    public function mytgm()
    {
    }

    /*
     * 我的收藏
     */
    public function mycollect()
    {
    }

    /*
     * 优惠券
     */
    public function coupon()
    {
    }

    /*
     * 我的地址
     */
    public function address()
    {
    }

    /*
     *意见反馈
     */
    public function mysugesst()
    {
    }
}
