<?php
/**
 * Created by PhpStorm.
 * User: wm
 * Date: 2018/3/13
 * Time: 17:57.
 */

namespace app\admin\controller;

use think\Db;

/**
 * 行为控制器
 * Author: zfc000000.
 */
class Info extends Admin
{
    /* public function _initialize()
     {
         parent::_initialize(); // TODO: Change the autogenerated stub
     }*/
    //商品列表
    public function index()
    {
        $model = Db::name('info');
        if (request()->isPost()) {
            $data = $_POST;
            if ($_FILES['file']['name']) {
                $path = $this->upfile('file');
                $data['pic_img'] = '/upload/images/'.$path;
            }
            $up = $model->where('id', 1)->update($data);
            $this->success('操作成功');
        }
        $item = $model->where('id', 1)->find();
        $rebate = json_decode($item['refundcontent'], true);
        $this->assign('rebate', $rebate);
        $this->assign('item', $item);
        $this->assign('meta_title', '小程序配置');

        return $this->fetch();
    }
}
