<?php
/*
 * @Descripttion:
 * @version:
 * @Author: zfc
 * @Date: 2020-10-27 17:09:25
 * @LastEditors: zfc
 * @LastEditTime: 2020-11-23 11:00:41
 */
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/10/22
 * Time: 15:13.
 */

namespace  app\index\controller;

use think\Controller;

class Index extends Controller
{
    protected function _initialize()
    {
        $this->uid = 1;
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        header('Location:'.'/index.html');
    }

    public function index2()
    {
        $uid = $this->uid;
        $this->assign('fromid', $uid);

        return $this->fetch();
    }

    public function medetail()
    {
        $fromid = $this->uid;
        $toid = input('toid');
        $this->assign('fromid', $fromid);
        $this->assign('toid', $toid);

        return $this->fetch();
    }
}
