<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/10/22
 * Time: 15:43
 */

namespace app\index\controller;


use think\Controller;

class Shop extends Controller
{

    protected function _initialize()
    {
        $this->sid=1;
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index(){
        $sid=$this->sid;
        $this->assign('fromid',$sid);
        return $this->fetch();
    }
    public function medetail(){
        $fromid =$this->sid;
        $toid =  input('toid');
        $this->assign('fromid',$fromid);
        $this->assign('toid',$toid);
        return $this->fetch();
    }

}