<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/9/23
 * Time: 16:29
 */

namespace app\apishop\controller;


use think\Db;

class Supcustom extends Supbase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //下单用户列表
    public function index(){
        $sid = $this->sid;//商户ID
        $types=intval($_REQUEST['types']);//记录类型0：下单客户，1：来访客户

        if($types==1){
            //来访客户
            $maporder['sid']=array('eq',$sid);
            //获取用户ID
            $userlist=Db::name('vister')->where($maporder)->group("uid")->field('uid')->select();
            $uids=array();
            foreach ($userlist as $key=>$val){
                $uids[$key]=$val['uid'];
            }

        }else{
            //客户管理
            $maporder['sid']=array('eq',$sid);
            //获取用户ID
            $userlist=Db::name('shop_order')->where($maporder)->group("user_id")->field('user_id')->select();
            $uids=array();
            foreach ($userlist as $key=>$val){
                $uids[$key]=$val['user_id'];
            }
        }
        if(!$uids){
            $data=array(
                'userlist'=>array(),
                'status'=>1,
                'usercount'=>0,
            );
            _success('获取成功',200,$data);
        }
        $page = intval($_REQUEST['page'])?intval($_REQUEST['page']):1;
        $onepagenum=$this->onepagenum;
        $limit = intval($page-1)*$onepagenum;
        $whereuser['uid']=array('in',$uids);

        $usercount=Db::name("user")->where($whereuser)->count();
        $user=Db::name("user")->where($whereuser)->field('uid,nickname,realname,mobile,headimgurl')->limit($limit.','.$onepagenum)->select();
        foreach($user as &$v){
            if($v['headimgurl']){
                $v['headimgurl']=__DATAURL__.$v['headimgurl'];
            }
            $v['mobilestr']=substr_replace($v['mobile'], '****', 3, 4);
            $maptag=array();
            $maptag['sid']=$sid;
            $maptag['uid']=$v['uid'];
            $v['tag']=Db::name('sid_uid')->where($maptag)->order('id desc')->value('tag');
            $addtime='';
            $addtime=Db::name('vister')->where($maptag)->order('addtime desc')->value('addtime');
            $v['addtime']=$addtime?$addtime:time();
            $v['addtime_day']=$addtime?date('y-m-d',$addtime):date('y-m-d',time());
            $v['vnumber']=Db::name('vister')->where($maptag)->count();
        }
        $data=array(
            'userlist'=>$user,
            'status'=>1,
            'usercount'=>$usercount?$usercount:'0',
        );
        _success('获取成功',200,$data);
    }

    //用户详情
    public function custdetail(){
        $sid = $this->sid;//商户ID
        $uid=intval($_REQUEST['uid']);//记录类型0：下单客户，1：来访客户
        if($uid>0){
            $whereuser['uid']=$uid;
            $userinfo=Db::name("user")->where($whereuser)->field('uid,nickname,realname,mobile,headimgurl')->find();
            if($userinfo){
                $userinfo['mobilestr']=substr_replace($userinfo['mobile'], '****', 3, 4);
                $maptag['sid']=$sid;
                $maptag['uid']=$userinfo['uid'];
                $userinfo['tag']=Db::name('sid_uid')->where($maptag)->order('id desc')->value('tag');
                $addtime=Db::name('vister')->where($maptag)->order('addtime desc')->value('addtime');
                $userinfo['addtime']=$addtime?$addtime:time();
                $userinfo['addtime_day']=$addtime?date('y-m-d',$addtime):date('y-m-d',time());
                $userinfo['vnumber']=Db::name('vister')->where($maptag)->count();
            }


            $data=array(
                'userinfo'=>$userinfo,
                'status'=>1,
            );
            _success('获取成功',200,$data);

        }else{
            _internalError('用户信息有误',500,'');
        }
    }

    //用户标签
    public function custtag(){
        $sid = $this->sid;//商户ID
        $uid=intval($_REQUEST['uid']);//记录类型0：下单客户，1：来访客户
        if($uid>0){
            $wheretag['sid']=$sid;
            $wheretag['uid']=$uid;
            $taginfo=Db::name("sid_uid")->where($wheretag)->find();
            $data['sid']=$sid;
            $data['uid']=$uid;
            $data['tag']=$_POST["tag"];//标签
            if($taginfo){
                //修改标签
                Db::name("sid_uid")->insertGetId($data);
            }else{
                //添加标签
                Db::name("sid_uid")->where($wheretag)->update($data);
            }
            $data=array(
                'tag'=>$data['tag'],
                'status'=>1,
            );
            _success('修改成功',200,$data['tag']);

        }else{
            _internalError('修改失败','500','');
        }

    }
}