<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/9/23
 * Time: 16:24
 * desc:消息
 */

namespace app\apishop\controller;


class Supmessage extends Supbase
{
        public function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub
        }
       //消息列表
        public function index(){

            $data=array(
                'usermes'=>'',
                'sysmes'=>'',
            );
            _success('获取成功',200,$data);
        }
        //消息详情
        public function mesdet(){

        }
}