<?php
/**
 * Created by PhpStorm.
 * User: BikeVR
 * Date: 2020/9/22
 * Time: 16:05
 * desc:商家中心.
 */

namespace app\apishop\controller;

use think\Db;

class Supuser extends Supbase
{
    /*
     *
     * 商家中心
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $sid = $this->sid;

        //商家中心导航设置
        $mapcate['is_show'] = ['eq', 1];
        $cate = Db::name('cate')->where($mapcate)->order('sort_order asc,id asc')->select();
        foreach ($cate as &$v) {
            if ($v['img']) {
                $v['img'] = __DATAURL__.$v['img'];
            }
        }
        //商户账户验证
        $supuser = Db::name('supuser')->where(['sid' => $sid])->field('sid,shopname,mobile,sex,headimgurl,status,city')->find();
        $data = [
            'shop' => $supuser,
            'cate' => $cate,
            'webtitle' => '商家中心',
        ];
        _success('获取成功', '200', $data);
    }

    //红点通知
    public function mescount()
    {
        //TODO 获取正确数据
        $data = [
            'Pendcount' => 2, //待处理数据
            'messcount' => 3, //消息数据
            'webtitle' => '', //标题
        ];
        _success('获取成功', '200', $data);
    }

    //商家个人中心
    public function shopindex()
    {
        $sid = $this->sid;
        $supuser = Db::name('supuser')->where(['sid' => $sid])->find();
        unset($supuser['password']);
        $b = [];
        if ($supuser['piccs']) {
            $img = explode(',', $supuser['piccs']);
            foreach ($img as $k => $v) {
                $b[] = __DATAURL__.$v;
            }
        }
        $supuser['pics_arr'] = $b;
        if ($supuser['bigpic']) {
            $supuser['bigpic'] = __DATAURL__.$supuser['bigpic'];
        }
        $supuser['headimgurl2'] = '';
        if ($supuser['headimgurl']) {
            $supuser['headimgurl2'] = $supuser['headimgurl'];
            $supuser['headimgurl'] = __DATAURL__.$supuser['headimgurl'];
        }
        $data = [
            'shop' => $supuser,
            'webtitle' => '我的店铺',
        ];
        _success('获取成功', '200', $data);
    }

    //商家信息管理
    public function shopedit()
    {
        $sid = $this->sid;
        $supuser = Db::name('supuser')->where(['sid' => $sid])->find();
        unset($supuser['password']);
        $ac = _param('op', '', 'index', false);
        if ($ac == 'edit') {
            $data['headimgurl'] = _param('pic', '请上传店铺头像');
            $data['headimgurl'] = str_replace(__DATAURL__, '', $data['headimgurl']);
            $data['shopname'] = _param('shopname', '请填写店铺名称');
            $data['type'] = _param('type', '请选择主营类型');
            $data['bigpic'] = _param('bigpic', '请上传店铺大图');
            $data['bigpic'] = str_replace(__DATAURL__, '', $data['bigpic']);
            $data['malltype'] = _param('malltype', '请选择物流方式');
            $data['city'] = _param('city', '请选择区域');
            // $data['cityid']= _param('city','请选择区域id');
            $data['address'] = _param('address', '请填写地址');
            $data['piccs'] = _param('piccs', '上传多图');
            $data['piccs'] = str_replace(__DATAURL__, '', $data['piccs']);
            $data['detail'] = _param('detail', '店铺信息');
            $shop = db('supuser');
            $ret = $shop->where('sid', $sid)->update($data);
            if ($ret) {
                _success('修改成功', 200, '');
            }
            _internalError('修改失败');
        } else {
            $b = [];
            if ($supuser['piccs']) {
                $img = explode(',', $supuser['piccs']);
                foreach ($img as $k => $v) {
                    $b[] = $v;
                }
            }
            $supuser['pics_arr'] = $b;
            if ($supuser['bigpic']) {
                $supuser['bigpic'] = $supuser['bigpic'];
            }
            $supuser['headimgurl2'] = '';
            if ($supuser['headimgurl']) {
                $supuser['headimgurl2'] = $supuser['headimgurl'];
                $supuser['headimgurl'] = $supuser['headimgurl'];
            }
            _success('获取成功', 200, $supuser);
        }
    }

    //商家结算中心
    public function mymoney()
    {
        $whe['sid'] = $this->sid;
        $page = intval($_REQUEST['page']) ? intval($_REQUEST['page']) : 1;
        $onepagenum = $this->onepagenum;
        $limit = intval($page - 1) * $onepagenum;
        $type = _param('mtype', '', '1', false); //快递类型
        $starttime = _param('starttime', '', time(), false); //开始时间
        $endtime = _param('endtime', '', time(), false); //结束时间
        $whe['malltype'] = ['eq', $type];
        $whe['stime'] = [['egt', $starttime], ['elt', $endtime], 'AND'];
        $orderlist = Db::name('shop_order')->where($whe)->limit($limit.','.$onepagenum)->select();
        $data = [
            'todaymoney' => 2, //今日结算金额
            'totalmoney' => 3, //历史结算金额
            'platformmoney' => 3, //平台金额
            'totaldealmoney' => 3, //总成交金额
            'orderlist' => $orderlist,
            'webtitle' => '结算中心', //标题
        ];
        _success('获取成功', '200', $data);
    }

    //商家结算详情
    public function moneydetail()
    {
        $sid = $this->sid;
        $orderid = _param('order_id', '订单编号');
        $order = Db::name('shop_order')
            ->where('sid', $sid)->where('id', $orderid)->find();
        if (!$order) {
            _internalError('信息错误', 500);
        }
        $data = [
            'orderinfo' => $order,
            'webtitle' => '结算详情', //标题
        ];
        _success('查找成功', 200, $data);
    }

    //商家版关于我们
    public function about()
    {
        $articl = [
            'title' => '快小驴',
            'banben' => 'V1.0',
            'icon' => '',
            'content' => '',
        ];
        $data = [
            'data' => $articl,
            'webtitle' => '关于我们', //标题
        ];
        _success('获取成功', 200, $data);
    }

    //商家更改密码
    public function changepass()
    {
        $phone = _param('phone', '手机号必须填写');
        $code = _param('code', '请输入验证码');
        $psw = _param('psw', '请输入新密码');
        $whe['sid'] = $this->sid;
        $whe['mobile'] = $phone;
        $shops = Db::name('supuser')->where($whe)->find();
        if (!$shops) {
            _internalError('信息错误');
        }
        //todo验证验证码正确与否
        $new['password'] = md5($psw);
        $res = Db::name('supuser')->where($whe)->update($new);
        if ($res) {
            _success('更改成功');
        } else {
            _internalError('未知错误');
        }
    }

    //营销中心
    public function marketing()
    {
        $vist = '';
        $data = [
            'vist' => $vist,
            'paycount' => $vist,
            'order' => $vist,
            'webtitle' => '营销管理', //标题
        ];
        _success('获取成功', 200, $data);
    }

    //验证手机号
    public function getmobile()
    {
        $mobile = $_POST['mobile'];
        $userid = intval($_POST['user_id']);
        $user = Db::name('user')->where('id', $userid)->find();
        if ($user['mobile'] != $mobile) {
            $count = Db::name('user')->where(['mobile' => $mobile])->count();
        }
        if ($count) {
            echo json_encode(['status' => 0, 'err' => '此手机号已经被注册']);
            exit;
        }
        //   $rand = rand(100000, 999999);

        $code = rand(100000, 999999); //生成6位随机密码
        $alidayu = new \alisms\SendSms();
        $t = $alidayu->ali_SendCode($mobile, $code);
        //$result=$this->send_Code($phone,$code);
        if (($t['Message'] == 'ok') && ($t['Code'] == 'ok')) {
            $d['code'] = $code;
            $d['mobile'] = $mobile;
            $d['addtime'] = time();
            $d['type'] = 2;
            Db::name('code')->insert($d);
            _success('发送成功', '200', '');
        }
        _internalError('发送失败');
        exit();

        //短信接口用户名 $uid
        $uid = 'LKSDK0007051';
        //短信接口密码 $passwd
        $passwd = 'zh9527@';
        //发送到的目标手机号码 $telphone
        $rand = rand(100000, 999999);
        $content = '您好，您的验证码是'.$rand.'，如果不是本人操作，请忽略【梦度软装】';
        $message = iconv('UTF-8', 'GBK', $content);
        $gateway = 'https://mb345.com/ws/BatchSend2.aspx?CorpID='.$uid.'&Pwd='.$passwd.'&Mobile='.$mobile.'&Content='.$message.'&Cell=&SendTime=';
        $res = file_get_contents($gateway);
        if ($res > 0) {
            echo json_encode(['status' => 1, 'scode' => $rand, 'stel' => $mobile, 'err' => '发送成功']);
            exit();
        } else {
            echo json_encode(['status' => 0, 'err' => $res]);
            exit();
        }
    }
}
