<?php
/**
 * Created by PhpStorm.
 * User: wm
 * Date: 2018/3/13
 * Time: 17:57
 */
namespace app\admin\controller;

use think\Db;
/**
 * 行为控制器
 * Author: zfc000000
 */

class Category extends Admin {

   /* public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }*/


    /*
     * 小程序导航
     */
    public function index(){
        $cate=$this->lists('cate','sort_order asc');
        $this->assign('cate',$cate);
        $this->assign('meta_title','栏目管理');
        return $this->fetch();
    }

    /**
     * 会员状态修改
     */
    public function changeStatus($method=null){
        $data=input('id/a');
        $id = array_unique($data);
        $id = is_array($id) ? implode(',',$id) : $id;
        if (empty($id) ) {
            $this->error('请选择要操作的数据!');
        }

        switch (strtolower($method) ){
            case 'delcate':
                $map['id'] =   array('in',$id);
                $mapor['pid'] =   array('in',$id);
                $res = Db::name('cate')->where($map)->whereOr($mapor)->delete();
                if($res){
                    $this->success('删除成功');
                }else{
                    $this->error('删除失败');
                }
                break;
            case 'ifshownavyes':
                $map['id'] =   array('in',$id);
                $data_in['is_show']=1;
                $res = Db::name('cate')->where($map)->update($data_in);
                if($res){
                    $this->success('状态更改成功');
                }else{
                    $this->error('状态更改失败');
                }
                break;
            case 'ifshownavno':
                $map['id'] =   array('in',$id);
                $data_in['is_show']=0;
                $res = Db::name('cate')->where($map)->update($data_in);
                if($res){
                    $this->success('状态更改成功');
                }else{
                    $this->error('状态更改失败');
                }
                break;
            case 'delcategory':
                $map['cat_id'] =   array('in',$id);
                $res = Db::name('category')->where($map)->delete();
                if($res){
                    $this->success('删除成功');
                }else{
                    $this->error('删除失败');
                }
                break;

            case 'delarttype':
                $map['id'] =   array('in',$id);
                $res = Db::name('arttype')->where($map)->delete();
                if($res){
                    $this->success('删除成功');
                }else{
                    $this->error('删除失败');
                }
                break;

            case 'delarticle':
                $map['id'] =   array('in',$id);
                $res = Db::name('article')->where($map)->delete();
                if($res){
                    $this->success('删除成功');
                }else{
                    $this->error('删除失败');
                }
                break;
            default:
                $this->error('参数非法');
        }
    }

    /*
     *
     * 导航菜单【添加、编辑】
     */
    public function addcate(){
        $id=input('id');
        if(request()->isPost()){
            $ids=$_POST['id'];
            
            $data=$_POST;
            /*$data['sort_order']=$data['sort_order'];//排序*/
            //var_dump($data);exit;
            if ($_FILES['file']['name']){
                $path=$this->upfile('file');
                $data['img']='/upload/images/'.$path;
            }
            if($ids){//如果存在 就是修改
                $up=Db::name('cate')->where('id',$ids)->update($data);
            }else{  //添加
                //   var_dump($data);
                $name=$data['name'];
                $data['addtime']=time();
                $oldtype=Db::name('cate')->where('name',$name)->find();
                if($oldtype){
                    $this->error('已存在该栏目名称');
                }
                $up=Db::name('cate')->insert($data);
            }
            if($up){
                $this->success('操作成功','category/index');
            }else{
                $this->error('操作失败');
            }
        }
        if($id){
            $category=Db::name('cate')->where('id',$id)->find();
            $this->assign('category',$category);
            $this->assign('meta_title','编辑栏目');
        }else{
            $this->assign('meta_title','添加栏目');
        }
        return $this->fetch();
    }

    

}